using GymFlow.Application.UseCases.Auditoria;
using GymFlow.Application.UseCases.Auth;
using GymFlow.Application.UseCases.Auth.Mfa;
using GymFlow.Application.UseCases.Empleados;
using GymFlow.Application.UseCases.Permisos;
using GymFlow.Application.UseCases.Planes;
using GymFlow.Application.UseCases.Portal;
using GymFlow.Application.UseCases.Roles;
using GymFlow.Application.UseCases.Socios;
using GymFlow.Application.UseCases.Cuotas;
using GymFlow.Application.UseCases.Clases;
using GymFlow.Application.UseCases.Eventos;
using GymFlow.Application.UseCases.Horarios;
using GymFlow.Application.UseCases.Inscripciones;
using GymFlow.Application.UseCases.Notificaciones;
using GymFlow.Application.UseCases.Unidades;

namespace GymFlow.API;

public static class DependencyInjection
{
    public static IServiceCollection AddApplication(this IServiceCollection services)
    {
        services.AddScoped<GetUnidadesQuery>();
        services.AddScoped<CreateSocioCommand>();
        services.AddScoped<GetSociosQuery>();
        services.AddScoped<DeleteSocioCommand>();
        services.AddScoped<GetPlanesQuery>();
        services.AddScoped<GetPlanByIdQuery>();
        services.AddScoped<CreatePlanCommand>();
        services.AddScoped<UpdatePlanCommand>();
        services.AddScoped<DeletePlanCommand>();
        services.AddScoped<ReactivatePlanCommand>();
        services.AddScoped<GetSocioByIdQuery>();
        services.AddScoped<UpdateSocioCommand>();
        services.AddScoped<ReactivateSocioCommand>();
        services.AddScoped<GetAuditoriaQuery>();
        services.AddScoped<GetRolesQuery>();
        services.AddScoped<GetRolByIdQuery>();
        services.AddScoped<GetPermisosQuery>();
        services.AddScoped<CrearRolCommand>();
        services.AddScoped<ActualizarRolCommand>();
        services.AddScoped<EliminarRolCommand>();
        services.AddScoped<GetEmpleadosQuery>();
        services.AddScoped<GetEmpleadoByIdQuery>();
        services.AddScoped<CrearEmpleadoCommand>();
        services.AddScoped<ActualizarEmpleadoCommand>();
        services.AddScoped<CambiarPasswordCommand>();
        services.AddScoped<DarDeBajaEmpleadoCommand>();
        services.AddScoped<ReactivarEmpleadoCommand>();
        services.AddScoped<GetSocioPerfilQuery>();
        services.AddScoped<SolicitarModificacionCommand>();
        services.AddScoped<SolicitarBajaCommand>();
        services.AddScoped<MarcarCuotaPagadaCommand>();
        services.AddScoped<AnularCuotaCommand>();
        services.AddScoped<GetCuotasBySocioQuery>();
        services.AddScoped<GetCuotasAdminQuery>();
        services.AddScoped<RevertirPagoCuotaCommand>();
        services.AddScoped<RevertirAnulacionCuotaCommand>();
        services.AddScoped<NotificarCuotaCommand>();
        services.AddScoped<ProcesarRecordatoriosCommand>();
        services.AddScoped<GetSociosConEstadoCuotaQuery>();
        services.AddScoped<GetClasesQuery>();
        services.AddScoped<GetClaseByIdQuery>();
        services.AddScoped<CreateClaseCommand>();
        services.AddScoped<UpdateClaseCommand>();
        services.AddScoped<CancelClaseCommand>();
        services.AddScoped<ReactivarClaseCommand>();
        services.AddScoped<GetHorariosQuery>();
        services.AddScoped<GetHorarioByIdQuery>();
        services.AddScoped<CreateHorarioCommand>();
        services.AddScoped<UpdateHorarioCommand>();
        services.AddScoped<DeleteHorarioCommand>();
        services.AddScoped<InscribirSocioCommand>();
        services.AddScoped<CancelarInscripcionCommand>();
        services.AddScoped<GetMisInscripcionesQuery>();
        services.AddScoped<GetEventosQuery>();
        services.AddScoped<GetEventoByIdQuery>();
        services.AddScoped<CrearEventoCommand>();
        services.AddScoped<ActualizarEventoCommand>();
        services.AddScoped<CancelarEventoCommand>();
        services.AddScoped<NotificarEventoCommand>();
        services.AddScoped<GetEventosPortalQuery>();
        services.AddScoped<GetNotificacionesQuery>();
        services.AddScoped<ContarNoLeidasQuery>();
        services.AddScoped<MarcarNotificacionLeidaCommand>();
        services.AddScoped<MarcarTodasLeidasCommand>();
        services.AddScoped<LoginConGoogleCommand>();
        services.AddScoped<IniciarMfaSetupCommand>();
        services.AddScoped<ActivarMfaCommand>();
        services.AddScoped<VerificarMfaCommand>();
        services.AddScoped<UsarCodigoRecuperacionCommand>();
        services.AddScoped<ResetearMfaEmpleadoCommand>();
        return services;
    }
}
