// <auto-generated />
using System;
using GymFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GymFlowDbContext))]
    partial class GymFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymFlow.Domain.Entities.Clase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UnidadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UnidadId");

                    b.ToTable("Clases", (string)null);
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Cuota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombrePlan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SocioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnidadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("SocioId");

                    b.HasIndex("UnidadId");

                    b.ToTable("Cuotas", (string)null);
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.HorarioClase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Sala")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId", "DiaSemana");

                    b.ToTable("HorariosClase", (string)null);
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.InscripcionClase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HorarioClaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SocioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HorarioClaseId");

                    b.HasIndex("SocioId");

                    b.ToTable("InscripcionesClase", (string)null);
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Modulo", "Operacion")
                        .IsUnique();

                    b.ToTable("Permisos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2700c7b-8aab-aff5-ad24-07f27b77f43b"),
                            Modulo = "Socios",
                            Operacion = "Lectura"
                        },
                        new
                        {
                            Id = new Guid("a31cd786-255b-16ac-e980-b899ee3e377b"),
                            Modulo = "Socios",
                            Operacion = "Escritura"
                        },
                        new
                        {
                            Id = new Guid("52c1feb8-98a7-3caa-35f5-df0f93d2a453"),
                            Modulo = "Socios",
                            Operacion = "Modificacion"
                        },
                        new
                        {
                            Id = new Guid("85236a48-46f3-3411-c68b-48b7d0bde83e"),
                            Modulo = "Socios",
                            Operacion = "Eliminacion"
                        },
                        new
                        {
                            Id = new Guid("0e3ccb52-631e-ab01-1b03-19eb3e0c166c"),
                            Modulo = "Planes",
                            Operacion = "Lectura"
                        },
                        new
                        {
                            Id = new Guid("46b1b86f-d5a2-efd5-a14b-f6e6cef155f1"),
                            Modulo = "Planes",
                            Operacion = "Escritura"
                        },
                        new
                        {
                            Id = new Guid("3db14f2d-e631-5d1f-998e-918eef77a623"),
                            Modulo = "Planes",
                            Operacion = "Modificacion"
                        },
                        new
                        {
                            Id = new Guid("cbeec377-4e4e-a9ec-c7e1-992e1b5fc994"),
                            Modulo = "Planes",
                            Operacion = "Eliminacion"
                        },
                        new
                        {
                            Id = new Guid("a84626b4-4e1f-d4df-62c1-bd5b66ed2da7"),
                            Modulo = "Unidades",
                            Operacion = "Lectura"
                        },
                        new
                        {
                            Id = new Guid("4cd6600e-0c61-1f71-600c-fb4de03dc59d"),
                            Modulo = "Unidades",
                            Operacion = "Escritura"
                        },
                        new
                        {
                            Id = new Guid("8e442f40-121a-eca9-23bc-54753ea7e6a7"),
                            Modulo = "Unidades",
                            Operacion = "Modificacion"
                        },
                        new
                        {
                            Id = new Guid("e1906bb1-c65d-7ea9-5ddf-43679e4e4434"),
                            Modulo = "Unidades",
                            Operacion = "Eliminacion"
                        },
                        new
                        {
                            Id = new Guid("7cf53e27-0f70-c8a4-5047-d7468049499c"),
                            Modulo = "Auditoria",
                            Operacion = "Lectura"
                        },
                        new
                        {
                            Id = new Guid("e0f92edd-c527-1b18-01a9-fec699383efb"),
                            Modulo = "Auditoria",
                            Operacion = "Escritura"
                        },
                        new
                        {
                            Id = new Guid("67bd9ddb-74f0-a5da-ce55-4147ce6f5e64"),
                            Modulo = "Auditoria",
                            Operacion = "Modificacion"
                        },
                        new
                        {
                            Id = new Guid("a89d7550-6895-cb7c-c50c-2c3757eb0d7f"),
                            Modulo = "Auditoria",
                            Operacion = "Eliminacion"
                        },
                        new
                        {
                            Id = new Guid("c75a7329-9ecf-23de-168b-df43e5d82268"),
                            Modulo = "Empleados",
                            Operacion = "Lectura"
                        },
                        new
                        {
                            Id = new Guid("5301567d-6106-30f0-f64c-726bfe81634c"),
                            Modulo = "Empleados",
                            Operacion = "Escritura"
                        },
                        new
                        {
                            Id = new Guid("5171a06c-b17d-4f3d-3d99-8aa4d8321c38"),
                            Modulo = "Empleados",
                            Operacion = "Modificacion"
                        },
                        new
                        {
                            Id = new Guid("49569ee3-9b6b-e594-865a-6dd30f40aa88"),
                            Modulo = "Empleados",
                            Operacion = "Eliminacion"
                        },
                        new
                        {
                            Id = new Guid("ef6441ba-c16e-cc6b-45a5-9e6375feb16d"),
                            Modulo = "Cuotas",
                            Operacion = "Lectura"
                        },
                        new
                        {
                            Id = new Guid("637b6d39-ebbf-9e16-8d7e-396861bd62ed"),
                            Modulo = "Cuotas",
                            Operacion = "Escritura"
                        },
                        new
                        {
                            Id = new Guid("47bf3159-8b32-a19a-0d37-af59a58a5f73"),
                            Modulo = "Cuotas",
                            Operacion = "Modificacion"
                        },
                        new
                        {
                            Id = new Guid("efd06b26-0147-c35f-9b0e-a7d6b57194e1"),
                            Modulo = "Cuotas",
                            Operacion = "Eliminacion"
                        },
                        new
                        {
                            Id = new Guid("c8aa70e1-cd1a-b8d7-e3d8-5fb9c20eb0c8"),
                            Modulo = "Clases",
                            Operacion = "Lectura"
                        },
                        new
                        {
                            Id = new Guid("1a3c6f4b-04a1-5fab-f185-742b93489621"),
                            Modulo = "Clases",
                            Operacion = "Escritura"
                        },
                        new
                        {
                            Id = new Guid("d44e2085-d440-af40-9121-82c745f8e7c8"),
                            Modulo = "Clases",
                            Operacion = "Modificacion"
                        },
                        new
                        {
                            Id = new Guid("7259fbb5-4c0b-1df4-e552-20fb3c1c9e94"),
                            Modulo = "Clases",
                            Operacion = "Eliminacion"
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UnidadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UnidadId");

                    b.ToTable("Planes", (string)null);
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.RecordatorioCuota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CuotaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SocioId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoRecordatorio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.HasIndex("CuotaId", "TipoRecordatorio", "FechaEnvio");

                    b.ToTable("RecordatoriosCuota", (string)null);
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.RegistroAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DetallesCambios")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EntidadAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TipoAccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EntidadId");

                    b.HasIndex("FechaHora")
                        .IsDescending();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistrosAuditoria", (string)null);
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            EsSistema = true,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            EsSistema = true,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Socio"
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.RolPermiso", b =>
                {
                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uuid");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolPermisos", (string)null);

                    b.HasData(
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("c2700c7b-8aab-aff5-ad24-07f27b77f43b")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("a31cd786-255b-16ac-e980-b899ee3e377b")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("52c1feb8-98a7-3caa-35f5-df0f93d2a453")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("85236a48-46f3-3411-c68b-48b7d0bde83e")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("0e3ccb52-631e-ab01-1b03-19eb3e0c166c")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("46b1b86f-d5a2-efd5-a14b-f6e6cef155f1")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("3db14f2d-e631-5d1f-998e-918eef77a623")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("cbeec377-4e4e-a9ec-c7e1-992e1b5fc994")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("a84626b4-4e1f-d4df-62c1-bd5b66ed2da7")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("4cd6600e-0c61-1f71-600c-fb4de03dc59d")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("8e442f40-121a-eca9-23bc-54753ea7e6a7")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("e1906bb1-c65d-7ea9-5ddf-43679e4e4434")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("7cf53e27-0f70-c8a4-5047-d7468049499c")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("e0f92edd-c527-1b18-01a9-fec699383efb")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("67bd9ddb-74f0-a5da-ce55-4147ce6f5e64")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("a89d7550-6895-cb7c-c50c-2c3757eb0d7f")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("c75a7329-9ecf-23de-168b-df43e5d82268")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("5301567d-6106-30f0-f64c-726bfe81634c")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("5171a06c-b17d-4f3d-3d99-8aa4d8321c38")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("49569ee3-9b6b-e594-865a-6dd30f40aa88")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("ef6441ba-c16e-cc6b-45a5-9e6375feb16d")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("637b6d39-ebbf-9e16-8d7e-396861bd62ed")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("47bf3159-8b32-a19a-0d37-af59a58a5f73")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("efd06b26-0147-c35f-9b0e-a7d6b57194e1")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("c8aa70e1-cd1a-b8d7-e3d8-5fb9c20eb0c8")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("1a3c6f4b-04a1-5fab-f185-742b93489621")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("d44e2085-d440-af40-9121-82c745f8e7c8")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("7259fbb5-4c0b-1df4-e552-20fb3c1c9e94")
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Unidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Unidades", (string)null);
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("RolId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", (string)null);

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.UsuarioUnidad", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnidadId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid");

                    b.HasKey("UsuarioId", "UnidadId");

                    b.HasIndex("PlanId");

                    b.HasIndex("UnidadId");

                    b.ToTable("UsuarioUnidades", (string)null);
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Empleado", b =>
                {
                    b.HasBaseType("GymFlow.Domain.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Empleado");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Apellido = "Inicial",
                            Correo = "admin@gymflow.com",
                            EstaActivo = true,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Admin",
                            PasswordHash = "$2a$11$8TnD1uScCjtswRRfjtIMDufn8npEr3r1lKxd/aJ6LCv9wFtEPjvXS",
                            RolId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Socio", b =>
                {
                    b.HasBaseType("GymFlow.Domain.Entities.Usuario");

                    b.Property<bool>("ConsentimientoInformado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ConsentimientoTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentoIdentidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoBaja")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Socio");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Clase", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Unidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Cuota", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymFlow.Domain.Entities.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymFlow.Domain.Entities.Unidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Socio");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.HorarioClase", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Clase", "Clase")
                        .WithMany()
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.InscripcionClase", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.HorarioClase", "HorarioClase")
                        .WithMany()
                        .HasForeignKey("HorarioClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymFlow.Domain.Entities.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HorarioClase");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Plan", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Unidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.RecordatorioCuota", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Cuota", "Cuota")
                        .WithMany()
                        .HasForeignKey("CuotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymFlow.Domain.Entities.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuota");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.RolPermiso", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymFlow.Domain.Entities.Rol", "Rol")
                        .WithMany("Permisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.UsuarioUnidad", b =>
                {
                    b.HasOne("GymFlow.Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GymFlow.Domain.Entities.Unidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymFlow.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UnidadesAsignadas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Unidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Permisos");
                });

            modelBuilder.Entity("GymFlow.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UnidadesAsignadas");
                });
#pragma warning restore 612, 618
        }
    }
}
